parameters:
#    exam_manage.example.class: Exam\ManageBundle\Example

services:
#    exam_manage.example:
#        class: %exam_manage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
