parameters:
#    core_level.example.class: Core\LevelBundle\Example

services:
#    core_level.example:
#        class: %core_level.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        
