parameters:
    level_manager.class:  Core\LevelBundle\Doctrine\LevelManager
    level_manager.entity: Core\LevelBundle\Entity\Level

services:
    level_manager:
        class: %level_manager.class%
        arguments: ["@fos_user.entity_manager", %level_manager.entity%]