parameters:
#    mailer_email.example.class: Mailer\EmailBundle\Example

services:
#    mailer_email.example:
#        class: %mailer_email.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
