<?php

namespace Core\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagsByName($names)
    {
        $names = array_map('trim', $names);
        
        $qb = $this->createQueryBuilder('a')
                    ->where('a.name IN (:names)')
                    ->setParameters(array('names'=> $names));
        
        return $qb->getQuery();
    }
}