parameters:
#    shop_order.example.class: Shop\OrderBundle\Example

services:
#    shop_order.example:
#        class: %shop_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
