<?php

namespace Core\LevelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends EntityRepository
{
    
    public function getLevels(){
        
        return $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->getQuery()
                ->getResult();
        
    }
    
}

/*
<span class="label">Default</span>
Success 	<span class="label label-success">Success</span>
Warning 	<span class="label label-warning">Warning</span>
Important 	<span class="label label-important">Important</span>
Info            <span class="label label-info">Info</span>
Inverse 	<span class="label label-inverse">Inverse</span>
 */