<?php

namespace Core\LevelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends EntityRepository
{
    
    public function getLevels(){
        
        return $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->getQuery()
                ->getResult();
        
    }
    
}