<?php

namespace Mailer\EmailBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Security\RegistrationBundle\Event\UserConfirmationEvent;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    
    public function checkActivation($email, $activationKey, $dispatcher)
    {
        
        $email = $this->findOneBy(array('recipient'=>$email, 'activationkey'=>$activationKey));
        
        if($email){
            $dispatcher->dispatch('user.email.confirmed', new UserConfirmationEvent($email));
        }
        
        //exit;
        
        
    }
    
}
