<?php

namespace Exam\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamAnswerRepository extends EntityRepository
{
}
