<?php

namespace Exam\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends EntityRepository
{
    public function findByUser($user)
    {
      
        
        $repository = $this->getEntityManager()->getRepository('ExamCoreBundle:Exam');

        $query = $repository->createQueryBuilder('p')
                            ->where('p.id = :id')
                            ->setParameter('id', 1)
                            ->getQuery();

        $exam = $query->getResult();
        
        
        
        
        return $exam;
        
        /*
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, c FROM CoreQuestionBundle:Question p
                JOIN p.answers c
                    WHERE p.title = :title'
            )->setParameter('title', $title);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
         * 
         */
    }
}
