security_login:
    pattern:  /login/
    defaults: { _controller: SecurityAuthenticateBundle:Login:index }
    
security_register:
    pattern:  /register/
    defaults: { _controller: SecurityAuthenticateBundle:Registration:register }
    
security_confirmed:
    pattern: /confirmed/
    defaults: { _controller: SecurityAuthenticateBundle:Registration:confirmed }

