parameters:
#    shop_payment.example.class: Shop\PaymentBundle\Example

services:
#    shop_payment.example:
#        class: %shop_payment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
