imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true
    
swiftmailer:
    disable_delivery: true   

#swiftmailer:
#    delivery_address: me@example.com

doctrine:
    dbal:
        # add "_test" to the database name you set in parameters.ini:

        dbname:   %database_name%_dev
                


server_grove_translation_editor:
    storage:
        type: server_grove_translation_editor.storage.orm
        manager: doctrine.orm.entity_manager