api_rest:
    resource: "@ApiRestBundle/Resources/config/routing.yml"
    prefix:   /api

ConnectContactBundle:
    resource: "@ConnectContactBundle/Resources/config/routing.yml"
    prefix:   /contacts

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
acme_oauth_server_security:
    resource: "@ApiOauthBundle/Resources/config/security.yml"
    prefix:   /
    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

api_oauth:
    resource: "@ApiOauthBundle/Resources/config/routing.yml"
    prefix:   /

site_homepage:
    resource: "@SiteHomepageBundle/Resources/config/routing.yml"
    prefix:   /

question_comment:
    resource: "@QuestionCommentBundle/Resources/config/routing.yml"
    prefix:   /question

question_owner:
    resource: "@QuestionOwnerBundle/Resources/config/routing.yml"
    prefix:   /question

question_approved:
    resource: "@QuestionApprovedBundle/Resources/config/routing.yml"
    prefix:   /question

question_feedback:
    resource: "@QuestionFeedbackBundle/Resources/config/routing.yml"
    prefix:   /question

exam_manage:
    resource: "@ExamManageBundle/Resources/config/routing.yml"
    prefix:   /exam/

exam_generate:
    resource: "@ExamGenerateBundle/Resources/config/routing.yml"
    prefix:   /exam/

exam_practice:
    resource: "@ExamPracticeBundle/Resources/config/routing.yml"
    prefix:   /exam/

shop_payment:
    resource: "@ShopPaymentBundle/Resources/config/routing.yml"
    prefix:   /shop

question_review:
    resource: "@QuestionReviewBundle/Resources/config/routing.yml"
    prefix:   /question

question_create:
    resource: "@QuestionCreateBundle/Resources/config/routing.yml"
    prefix:   /question

security_registration:
    resource: "@SecurityRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

mailer_mail:
    resource: "@MailerMailBundle/Resources/config/routing.yml"
    prefix:   /

security_authenticate:
    resource: "@SecurityAuthenticateBundle/Resources/config/routing.yml"
    prefix:   /

DmAdminBundle:
    resource: "@DmAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

DmQuestionBundle:
    resource: "@DmQuestionBundle/Resources/config/routing.yml"
    prefix:   /question

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
