site_plan_pricing:
    pattern: /plan-and-pricing
    defaults: { _controller: SiteHomepageBundle:Pricing:index }

SiteHomepageBundle_Page_Index_Index:
    pattern:  /
    defaults: { _controller: SiteHomepageBundle:Default:index }
