DmAdminBundle_question_edit:
    pattern:  /question/edit/{id}
    defaults: { _controller: DmAdminBundle:Question:edit }
    requirements:
        id:  \d+

DmAdminBundle_question_create:
    pattern:  /question/create
    defaults: { _controller: DmAdminBundle:Question:create }
    
DmAdminBundle_question_list:
    pattern:  /question
    defaults: { _controller: DmAdminBundle:Question:index }    

DmAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: DmAdminBundle:Default:index }
