parameters:
#    dm_admin.example.class: Dm\AdminBundle\Example

services:
#    dm_admin.example:
#        class: %dm_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
