parameters:
    comment_manager.class:  Core\CommentBundle\Doctrine\CommentManager
    comment_manager.entity: Core\CommentBundle\Entity\Comment

services:
    comment_manager:
        class: %comment_manager.class%
        public: false
        arguments: ["@fos_user.entity_manager", %comment_manager.entity%]