<?php

namespace Security\AuthenticateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    
    public function activateUser($email)
    {
        
        
        $user = $this->findOneBy(array('email'=>$email));
        var_dump($user);
        
        
    }
    
}

