parameters:
    registration_manager.class:  Security\RegistrationBundle\Doctrine\RegistrationManager
    registration_manager.entity: Security\AuthenticateBundle\Entity\User

services:
#    security_registration.example:
#        class: %security_registration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    security_bundle.listener.registration_confirmed:
        class: Security\RegistrationBundle\Listener\RegistrationListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: user.email.confirmed, method: onConfirmed }
            
            
    security.registration_manager:
        class: %registration_manager.class%
        arguments: ["@fos_user.entity_manager", %registration_manager.entity%]