parameters:
    type_manager.class:  Core\TypeBundle\Doctrine\TypeManager
    type_manager.entity: Core\TypeBundle\Entity\Type

services:
    type_manager:
        class: %type_manager.class%
        public: false
        arguments: ["@fos_user.entity_manager", %type_manager.entity%]