parameters:
#    account_admin.example.class: Account\AdminBundle\Example

services:
#    account_admin.example:
#        class: %account_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
