parameters:
    my_mailer.class: Mailer\MailBundle\Mailer\Mailer
    email_listener.class: Mailer\MailBundle\Listener\MailerListener
    
    email_registration_doctrine.class: Mailer\EmailBundle\Doctrine\EmailRegistrationManager
    email_registration.object: Mailer\EmailBundle\Entity\RegistrationEmail
    
    email_resetting_doctrine.class: Mailer\EmailBundle\Doctrine\EmailResettingManager
    email_resetting.object: Mailer\EmailBundle\Entity\ResettingEmail
    
    email_question_submission_doctrine.class: Mailer\EmailBundle\Doctrine\EmailQuestionSubmissionManager
    email_question_submission_doctrine.object: Mailer\EmailBundle\Entity\QuestionSubmissionEmail

services:
#    mailer_mail.example:
#        class: %mailer_mail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my_mailer:
        class:  %my_mailer.class%
        arguments:
            - "@service_container"
            
    mailer_bundle.listener.email:
        class: Mailer\MailBundle\Listener\EmailListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: email.message.save, method: onSave }
            
                
    email_registration_doctrine:
        class: %email_registration_doctrine.class%
        arguments:  ["@fos_user.entity_manager", %email_registration.object%]     
        
    email_resetting_doctrine:
        class: %email_resetting_doctrine.class%
        arguments:  ["@fos_user.entity_manager", %email_resetting.object%]  
        
    email_question_submission_doctrine:
        class: %email_question_submission_doctrine.class%
        arguments:  ["@fos_user.entity_manager", %email_question_submission_doctrine.object%]  
