parameters:
#    behat_behat.example.class: Behat\BehatBundle\Example

services:
#    behat_behat.example:
#        class: %behat_behat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
