parameters:
#    dm_question.example.class: Dm\QuestionBundle\Example

services:
#    dm_question.example:
#        class: %dm_question.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    dbla.testapp.admin.product:
        class: Dm\QuestionBundle\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: TestYourSkills, label: question }
        arguments: [null, Dm\QuestionBundle\Entity\Question, SonataAdminBundle:CRUD]