parameters:
#    dm_question.example.class: Dm\QuestionBundle\Example

services:
#    dm_question.example:
#        class: %dm_question.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
