parameters:
    question_manager.class:  Core\QuestionBundle\Doctrine\QuestionManager
    question_manager.entity: Core\QuestionBundle\Entity\Question

services:
    question_manager:
        class: %question_manager.class%
        public: false
        arguments: ["@fos_user.entity_manager", %question_manager.entity%]