acme_oauth_server_auth_login:
  pattern: /oauth/v2/auth_login
  defaults: { _controller: AcmeOAuthServerBundle:Security:login }
  
acme_oauth_server_auth_login_check:
  pattern: /oauth/v2/auth_login_check
  defaults: { _controller: AcmeOAuthServerBundle:Security:loginCheck }