<?php

namespace Dm\QuestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    
    
    public function getQuestionQueryList(){
        
        $qb = $this->createQueryBuilder('a')
                   ->select('a, c','d', 'e','f')
                   ->leftJoin('a.section', 'c')
                   ->leftJoin('a.level', 'd')
                   ->leftJoin('a.type', 'e')
                   ->leftJoin('a.tags', 'f');
        
        //var_dump($qb->getQuery());
        //exit;
                   
        return $qb->getQuery();
        
    }
    
    
    public function getLevelColor($levels){
        
    }
}