parameters:
#    question_feedback.example.class: Question\FeedbackBundle\Example

services:
#    question_feedback.example:
#        class: %question_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
