# language: en
Feature: Generate Exam

    @javascript
    Scenario: Check the create exam functionality

        #Success with one section 
        Given   I am on "/app_dev.php/"
        Then    I follow "Login"
        Then    I wait 1 second
        Then    I fill in "user" for "username"
        And     I fill in "userpass" for "password"
        Then    I press "loginBtn"
        Then    I should see "Logged in as user"
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I check "Advanced"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        Then    I press "generateExam"
        Then    I should be on "/app_dev.php/exam/list/"

        #Success with multiple section 
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I check "Python"
        And     I check "C++"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I check "Advanced"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        Then    I press "generateExam"
        Then    I should be on "/app_dev.php/exam/list/"

        #Success with more than 5 tags 
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I check "Advanced"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        And     I check "arrays"
        And     I check "strings"
        And     I check "namespace"
        Then    I press "generateExam"
        Then    I should be on "/app_dev.php/exam/list/"

        #Failure without section 
        Given   I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I check "Advanced"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        Then    I press "generateExam"
        Then    I should see "You must choose at least one test"
        And     I should be on "/app_dev.php/exam/create"

        #Failure without number of candidates
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I check "Advanced"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        Then    I press "generateExam"
        # And     I should see "You must select a number of candidates"
        And     I should be on "/app_dev.php/exam/create"

        #Failure without number of questions
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I check "Advanced"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        Then    I press "generateExam"
        Then    I should see "You must select a number of questions"
        And     I should be on "/app_dev.php/exam/create"

        #Failure without level
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        Then    I press "generateExam"
        Then    I should see "You must select a level for this test"
        And     I should be on "/app_dev.php/exam/create"

        #Failure without types
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I check "Advanced"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        And     I check "PDO"
        And     I check "session"
        Then    I press "generateExam"
        Then    I should see "You must choose at least one type of question"
        And     I should be on "/app_dev.php/exam/create"

        #Failure without correct number of tags
        Then    I am on "/app_dev.php/exam/create"
        Then    I should see "Create your test"
        Then    I check "PHP"
        And     I fill in "5" for "exam_generate_form_numberCandidates"
        And     I check "Advanced"
        And     I fill in "10" for "exam_generate_form_numberQuestions"
        And     I check "multi-choice"
        And     I check "core"
        And     I check "variables"
        And     I check "file system"
        Then    I press "generateExam"
        Then    I should see "You must select at least 5 topics"
        And     I should be on "/app_dev.php/exam/create"
