parameters:
#    site_navigation.example.class: Site\NavigationBundle\Example

services:
#    site_navigation.example:
#        class: %site_navigation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
