parameters:
    section_manager.class:  Core\SectionBundle\Doctrine\SectionManager
    section_manager.entity: Core\SectionBundle\Entity\Section

services:
    section_manager:
        class: %section_manager.class%
        public: false
        arguments: ["@fos_user.entity_manager", %section_manager.entity%]