parameters:
#    core_section.example.class: Core\SectionBundle\Example

services:
#    core_section.example:
#        class: %core_section.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
