parameters:
    tag_manager.class:  Core\TagBundle\Doctrine\TagManager
    tag_manager.entity: Core\TagBundle\Entity\Tag

services:
    tag_manager:
        class: %tag_manager.class%
        arguments: ["@fos_user.entity_manager", %tag_manager.entity%]