parameters:
#    core_answer.example.class: Core\AnswerBundle\Example

services:
#    core_answer.example:
#        class: %core_answer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
