parameters:
    answer_manager.class:  Core\AnswerBundle\Doctrine\AnswerManager
    answer_manager.entity: Core\AnswerBundle\Entity\Answer

services:
#    core_answer.example:
#        class: %core_answer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    answer_manager:
        class: %answer_manager.class%
        public: false
        arguments: ["@fos_user.entity_manager", %answer_manager.entity%]