parameters:
#    question_approved.example.class: Question\ApprovedBundle\Example

services:
#    question_approved.example:
#        class: %question_approved.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
