QuestionCreateBundle_Page_Create_Success:
    pattern:  /created
    defaults: { _controller: QuestionCreateBundle:Create:success }

QuestionCreateBundle_Page_Create_Index:
    pattern:  /create
    defaults: { _controller: QuestionCreateBundle:Create:index }