question_create_success:
    pattern:  /created
    defaults: { _controller: QuestionCreateBundle:Create:success }

question_create_homepage:
    pattern:  /create
    defaults: { _controller: QuestionCreateBundle:Create:index }