question_create_test:
    pattern: /test
    defaults: { _controller: QuestionCreateBundle:Create:test }

question_create_homepage:
    pattern:  /create
    defaults: { _controller: QuestionCreateBundle:Create:index }
