parameters:
#    exam_core.example.class: Exam\CoreBundle\Example

services:
#    exam_core.example:
#        class: %exam_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
