parameters:
#    exam_candidate_manager.class:  Exam\CoreBundle\Doctrine\ExamCandidateManager
#    exam_candidate_manager.entity: Exam\CoreBundle\Entity\ExamCandidate

services:
#    exam_candidate.manager:
#        class: %exam_candidate_manager.class%
#        arguments: ["@fos_user.entity_manager", %exam_candidate_manager.entity%]
